# Generated by Django 6.0.1 on 2026-02-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(editable=False, help_text='Auto-generated Asset ID (e.g., AST-0001)', max_length=20, unique=True)),
                ('serial_number', models.CharField(max_length=100)),
                ('asset_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('model_id', models.CharField(max_length=100)),
                ('model_category', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('ci_name', models.CharField(blank=True, help_text='Configuration Item Name', max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Decommissioned', 'Decommissioned'), ('Maintenance', 'Maintenance')], default='Active', max_length=20)),
                ('dmr_status', models.CharField(choices=[('Pending', 'Pending'), ('Scanned', 'Scanned'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
